services:
  llama-swap-manager:
    image: ghcr.io/n3kr0nom1c0n/llama-swap-web:latest
    container_name: llama-swap-manager
    restart: unless-stopped
    user: "10001:10001"
    env_file:
      - path: .env
        required: false
    ports:
      - "8081:8081"
    volumes:
      - ./.env:/app/.env
      - /path/to/llama.cpp/models:/models
      - /path/to/llama-swap/config.yaml:/app/config.yaml
      - /path/to/llama-swap/backups:/backups
      - llama-swap-manager-data:/data

volumes:
  llama-swap-manager-data:
