export const queryKeys = {
  state: ["state"] as const,
  stateFor: (targetRigId: string) => ["state", targetRigId] as const,
  settings: ["settings"] as const,
  targetRigs: ["target-rigs"] as const,
  targetRigHealth: (targetRigId: string) => ["target-rigs", targetRigId, "health"] as const,
  llamaSwapStatus: ["llama-swap", "status"] as const,
  llamaSwapStatusFor: (targetRigId: string) => ["llama-swap", "status", targetRigId] as const,
  gpus: ["gpus"] as const,
  gpusFor: (targetRigId: string) => ["gpus", targetRigId] as const,
  gpuDetection: ["gpus", "detect"] as const,
  gpuDetectionFor: (targetRigId: string) => ["gpus", "detect", targetRigId] as const,
  gpuStatus: ["gpus", "status"] as const,
  gpuStatusFor: (targetRigId: string) => ["gpus", "status", targetRigId] as const,
  models: ["models"] as const,
  modelsFor: (targetRigId: string) => ["models", targetRigId] as const,
  downloads: ["downloads"] as const,
  downloadsFor: (targetRigId: string) => ["downloads", targetRigId] as const,
  modelScan: ["models", "scan"] as const,
  modelScanFor: (targetRigId: string) => ["models", "scan", targetRigId] as const,
  configBackups: ["config", "backups"] as const,
  configBackupsFor: (targetRigId: string) => ["config", "backups", targetRigId] as const,
  configImport: ["config", "import"] as const,
  configImportFor: (targetRigId: string) => ["config", "import", targetRigId] as const,
  preview: ["preview"] as const,
  previewFor: (targetRigId: string, selectedIds: string[]) => ["preview", targetRigId, selectedIds] as const,
};
